### PR TITLE
Added a more accessible chart.

### PR DESCRIPTION
**Pull request by sukiletxe**
Todo: add another chart with just the symbol and its unicode hex value and name.

### CODE REVIEW

**Comment by sukiletxe** [comment]
For the Unicode chart, is it okay if I adapt [the chart in John Wells' page](http://www.phon.ucl.ac.uk/home/wells/ipa-unicode.htm) changing naming where appropriate, removing the "decimal" column and adding the unicode name?

**Comment by westonruter** [comment]
I'm not sure, but feel free to make any changes you like. You may want to merge your changes into your own `gh-pages` branch, and you can have your own changes made available on your own account.

**Comment by sukiletxe** [comment]
Finally, this is done. However, those symbols were missing from your chart, and they were present on Wells':
* ʤ
* ɚ
* ʧ
* ʱ

On the other hand, those were missing from Wells' chart, but were present in your chart:
* ⁿ
* ˡ
* Almost all "contour" symbols, except for global rise and global fall

Which ones should I add to the file with the Unicode values?

**Comment by westonruter** [comment]
@sukiletxe 

> Which ones should I add to the file with the Unicode values?

Sorry, I'm really not sure. It's been so long since I've been active on this project that I'm not up to speed on what the state of the art is.

**Comment by sukiletxe** [comment]
After looking at the International Phonetic Association's website, I 
have decided to add all of the symbols, because some of them aren ot in 
the IPA chart but are still used.

**Comment by sukiletxe** [comment]
I think this is done. If you want me to do any changes before merging (merge various commits into one, reword them, etc.), feel free to ask.

**Comment by westonruter** [comment]
Thanks for the PR.

**Pull request merged**
